# Generated by Django 4.1.1 on 2022-09-06 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions', models.TextField()),
                ('ingredients', models.TextField()),
                ('prep_time', models.TimeField(null=True)),
                ('cook_time', models.TimeField(null=True)),
                ('photo', models.TextField()),
                ('name', models.CharField(max_length=150)),
                ('main_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='wineapi.mainingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Varietal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('varietal', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vintner', models.CharField(max_length=150)),
                ('vintage', models.IntegerField()),
                ('name', models.CharField(max_length=150)),
                ('varietal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wines', to='wineapi.varietal')),
            ],
        ),
        migrations.CreateModel(
            name='WineUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.TextField()),
                ('bio', models.TextField()),
                ('admin', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WineRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wine_rating', to='wineapi.wine')),
                ('wine_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wine_rating', to='wineapi.wineuser')),
            ],
        ),
        migrations.CreateModel(
            name='WineFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wine_favorites', to='wineapi.wine')),
                ('wine_user', models.ManyToManyField(related_name='wine_favorites', to='wineapi.wineuser')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_rating', to='wineapi.recipe')),
                ('wine_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_rating', to='wineapi.wineuser')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_favorites', to='wineapi.recipe')),
                ('wine_user', models.ManyToManyField(related_name='recipe_favorites', to='wineapi.wineuser')),
            ],
        ),
        migrations.CreateModel(
            name='PairingFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairing_favorites', to='wineapi.recipe')),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairing_favorites', to='wineapi.wine')),
                ('wine_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairing_favorites', to='wineapi.wineuser')),
            ],
        ),
    ]
