# Generated by Django 4.1.1 on 2022-09-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wineapi', '0002_remove_wine_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='serves',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cook_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep_time',
            field=models.IntegerField(null=True),
        ),
    ]
