# Generated by Django 4.1.1 on 2022-09-07 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wineapi', '0003_recipe_serves_alter_recipe_cook_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='favorite',
            field=models.ManyToManyField(related_name='recipes', through='wineapi.RecipeFavorite', to='wineapi.wineuser'),
        ),
        migrations.AddField(
            model_name='wine',
            name='favorite',
            field=models.ManyToManyField(related_name='favorite_wines', through='wineapi.WineFavorite', to='wineapi.wineuser'),
        ),
        migrations.AddField(
            model_name='wine',
            name='photo',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='wine',
            name='submitted_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_by_wines', to='wineapi.wineuser'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='recipefavorite',
            name='wine_user',
        ),
        migrations.RemoveField(
            model_name='winefavorite',
            name='wine_user',
        ),
        migrations.AddField(
            model_name='recipefavorite',
            name='wine_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_favorites', to='wineapi.wineuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='winefavorite',
            name='wine_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wine_favorites', to='wineapi.wineuser'),
            preserve_default=False,
        ),
    ]
