# Generated by Django 4.1.1 on 2022-09-13 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wineapi', '0005_rename_photo_recipe_summary_remove_recipe_cook_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='main_ingredient',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='wines', to='wineapi.mainingredient'),
            preserve_default=False,
        ),
    ]
