# Generated by Django 4.1.1 on 2022-09-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wineapi', '0006_wine_main_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wineuser',
            name='admin',
            field=models.BooleanField(verbose_name=False),
        ),
    ]
