# Generated by Django 4.1.1 on 2022-09-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wineapi', '0007_alter_wineuser_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wine',
            old_name='vintage',
            new_name='score',
        ),
        migrations.RenameField(
            model_name='wine',
            old_name='vintner',
            new_name='title',
        ),
        migrations.AddField(
            model_name='wine',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wine',
            name='link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wine',
            name='price',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='main_ingredient',
        ),
        migrations.RemoveField(
            model_name='wine',
            name='main_ingredient',
        ),
        migrations.AlterField(
            model_name='wine',
            name='photo',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='main_ingredient',
            field=models.ManyToManyField(related_name='recipes', to='wineapi.mainingredient'),
        ),
        migrations.AddField(
            model_name='wine',
            name='main_ingredient',
            field=models.ManyToManyField(related_name='wines', to='wineapi.mainingredient'),
        ),
    ]
