# Generated by Django 4.1.1 on 2022-09-22 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wineapi', '0008_rename_vintage_wine_score_rename_vintner_wine_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='main_ingredient',
        ),
        migrations.AlterField(
            model_name='wine',
            name='varietal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wines', to='wineapi.varietal'),
        ),
    ]
