# Generated by Django 4.1.1 on 2022-09-22 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wineapi', '0009_remove_recipe_main_ingredient_alter_wine_varietal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_by_wines', to='wineapi.wineuser'),
        ),
    ]
