# Generated by Django 4.1.1 on 2022-09-22 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wineapi', '0010_alter_wine_submitted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='main_ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='wineapi.mainingredient'),
        ),
        migrations.RemoveField(
            model_name='wine',
            name='main_ingredient',
        ),
        migrations.AddField(
            model_name='wine',
            name='main_ingredient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wines', to='wineapi.mainingredient'),
            preserve_default=False,
        ),
    ]
