# Generated by Django 4.1.1 on 2022-09-22 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wineapi', '0011_recipe_main_ingredient_remove_wine_main_ingredient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='main_ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wines', to='wineapi.mainingredient'),
        ),
    ]
